import Head from "next/head";

export default function SinglePostPage() {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-start bg-slate-800">
        <div className="mx-auto flex h-full w-full max-w-3xl flex-col items-start justify-start gap-12 border border-white">
          <div>Profile View</div>
        </div>
      </main>
    </>
  );
}
